/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}'],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "secondary": "#2b6954",
        "primary-fixed": "#6ffbbe",
        "on-secondary-fixed": "#002117",
        "background": "#f8f9ff",
        "on-error": "#ffffff",
        "outline-variant": "#bbcabf",
        "on-tertiary-fixed": "#001a42",
        "on-secondary-container": "#306d58",
        "secondary-fixed-dim": "#95d3ba",
        "tertiary-fixed": "#d8e2ff",
        "primary-fixed-dim": "#4edea3",
        "tertiary-fixed-dim": "#adc6ff",
        "tertiary": "#005ac2",
        "outline": "#6c7a71",
        "on-error-container": "#93000a",
        "error-container": "#ffdad6",
        "on-tertiary": "#ffffff",
        "on-secondary": "#ffffff",
        "on-tertiary-container": "#00367a",
        "on-surface-variant": "#3c4a42",
        "on-primary": "#ffffff",
        "error": "#ba1a1a",
        "surface-bright": "#f8f9ff",
        "secondary-fixed": "#b0f0d6",
        "surface-dim": "#cbdbf5",
        "on-primary-fixed-variant": "#005236",
        "surface": "#f8f9ff",
        "surface-container-lowest": "#ffffff",
        "inverse-surface": "#213145",
        "inverse-on-surface": "#eaf1ff",
        "surface-container-high": "#dce9ff",
        "surface-container-low": "#eff4ff",
        "tertiary-container": "#71a1ff",
        "secondary-container": "#adedd3",
        "primary": "#10B981",
        "primary-container": "#10b981",
        "surface-container": "#e5eeff",
        "on-surface": "#0b1c30",
        "on-background": "#0b1c30",
        "surface-variant": "#d3e4fe",
        "on-primary-fixed": "#002113",
        "surface-container-highest": "#d3e4fe",
        "on-secondary-fixed-variant": "#0b513d",
        "on-primary-container": "#00422b",
        "inverse-primary": "#4edea3",
        "on-tertiary-fixed-variant": "#004395",
        "surface-tint": "#006c49"
      },
      fontFamily: {
        "headline": ["Manrope", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"]
      },
      borderRadius: {"DEFAULT": "0.5rem", "lg": "0.75rem", "xl": "1rem", "full": "9999px"},
    },
  },
  plugins: [],
}
